spring:
  jpa:
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false

waschbaer:
  # default value of events monitor window in minutes
  default-events-time-window: 10

logging:
  level:
    root: INFO
    org.nantipov: DEBUG
